@startuml IDC LOL

hide empty description

state STATE_MONITORING
state STATE_INFERENCE
state STATE_COUNTDOWN
state STATE_ALERTING
state STATE_CANCELLED

[*] --> STATE_MONITORING : Setup complete

STATE_MONITORING --> STATE_INFERENCE : Naive detector triggered

STATE_INFERENCE --> STATE_MONITORING : False Alarm
STATE_INFERENCE --> STATE_COUNTDOWN : Fall detected

STATE_COUNTDOWN --> STATE_CANCELLED : Cancel button
STATE_COUNTDOWN --> STATE_ALERTING : 15-second timeout

STATE_ALERTING --> STATE_MONITORING : Reset or 40-second timeout

STATE_CANCELLED --> STATE_MONITORING : After 1 second

@enduml